const songs = [
  {id: 1, name: "Kesariya", song: song1, image: image1, category: "Romantic", liked: false, singer: "Arijit Singh"},
  {id: 2, name: "Besharam Rang", song: song2, image: image2, category: "Dance, Pop", liked: false, singer: "Shilpa Rao, Caralisa Monteiro"},
  {id: 3, name: "Srivalli", song: song3, image: image3, category: "Romantic", liked: false, singer: "Javed Ali"},
  {id: 4, name: "Chaleya", song: song4, image: image4, category: "Romantic, Pop", liked: false, singer: "Arijit Singh, Shilpa Rao"},
  {id: 5, name: "Not Ramaiya Vastavaiya", song: song5, image: image5, category: "Dance, Pop", liked: false, singer: "Anirudh Ravichander, Vishal Dadlani"},
  {id: 6, name: "Ishq Jaisa Kuch", song: song6, image: image6, category: "Dance, Pop", liked: false, singer: "Vishal Dadlani, Shekhar Ravjiani"},
  {id: 7, name: "Apna Bana Le", song: song7, image: image7, category: "Romantic", liked: false, singer: "Arijit Singh"},
  {id: 8, name: "Tum Kya Mile", song: song8, image: image8, category: "Romantic", liked: false, singer: "Arijit Singh, Shreya Ghoshal"},
  {id: 9, name: "Jhoome Jo Pathaan", song: song9, image: image9, category: "Dance", liked: false, singer: "Arijit Singh, Sukriti Kakar"},
  {id: 10, name: "Main Nikla Gaddi Leke (Remake)", song: song10, image: image10, category: "Dance, Nostalgic", liked: false, singer: "Udit Narayan, Aditya Narayan"},
  {id: 11, name: "Tere Pyaar Mein", song: song11, image: image11, category: "Romantic, Pop", liked: false, singer: "Arijit Singh, Nikhita Gandhi"},
  {id: 12, name: "Fitoor (Shamshera)", song: song12, image: image12, category: "Romantic", liked: false, singer: "Arijit Singh, Neeti Mohan"},
  {id: 13, name: "Daku", song: song13, image: image13, category: "Punjabi Rap", liked: false, singer: "Inderpal Moga"},
  {id: 14, name: "Kya Loge Tum", song: song14, image: image14, category: "Sad", liked: false, singer: "B Praak"},
  {id: 15, name: "Baarish Ban Jaana", song: song15, image: image15, category: "Romantic", liked: false, singer: "Stebin Ben, Payal Dev"},
  {id: 16, name: "Lut Gaye", song: song16, image: image16, category: "Romantic", liked: false, singer: "Jubin Nautiyal"},
  {id: 17, name: "Raatan Lambiyan", song: song17, image: image17, category: "Romantic", liked: false, singer: "Jubin Nautiyal, Asees Kaur"},
  {id: 18, name: "Mann Bharryaa 2.0", song: song18, image: image18, category: "Emotional, Sad", liked: false, singer: "B Praak"},
  {id: 19, name: "Meri Zindagi Hai Tu", song: song19, image: image19, category: "Romantic", liked: false, singer: "Jubin Nautiyal, Neeti Mohan"},
{id: 20, name: "Tu Hai Kahan", song: song20, image: image20, category: "Romantic, Pop", liked: false, singer: "AUR"},
{id: 21, name: "Ratiyaan", song: song21, image: image21, category: "Soulful, Romantic", liked: false, singer: " Hansika Pare"},
  {id: 22, name: "Galliyan Returns", song: song22, image: image22, category: "Romantic", liked: false, singer: "Ankit Tiwari"},
  {id: 23, name: "Phir Aur Kya Chahiye", song: song23, image: image23, category: "Romantic", liked: false, singer: "Arijit Singh"},
  {id: 24, name: "O Maahi", song: song24, image: image24, category: "Emotional", liked: false, singer: "Arijit Singh"},
  {id: 25, name: "Deva Deva", song: song25, image: image25, category: "Devotional, Pop", liked: false, singer: "Arijit Singh"},
  {id: 26, name: "Dil Jhoom", song: song26, image: image26, category: "Romantic", liked: false, singer: "Mithoon, Arijit Singh"},
  {id: 27, name: "O Bedardeya", song: song27, image: image27, category: "Sad, Emotional", liked: false, singer: "Arijit Singh"},
  {id: 28, name: "Jehda Nasha", song: song28, image: image28, category: "Dance", liked: false, singer: "Amar Jalal, IP Singh, Yohani, Harjot Kaur"},
  {id: 29, name: "Tere Vaaste", song: song29, image: image29, category: "Romantic", liked: false, singer: "Varun Jain, Sachin-Jigar, Shadab Faridi, Altamash Faridi"},
  {id: 30, name: "Chal Tere Ishq Mein", song: song30, image: image30, category: "Romantic", liked: false, singer: "Neeti Mohan, Saaj Bhatt"},
  {id: 31, name: "Hum Nashe Mein Toh Nahin", song: song31, image: image31, category: "Emotional", liked: false, singer: "Arijit Singh, Tulsi Kumar"},
  {id: 32, name: "Haan Tum Ho", song: song32, image: image32, category: "Romantic", liked: false, singer: "Arijit Singh"},
  {id: 33, name: "Munda Sona Hoon Main", song: song33, image: image33, category: "Dance, Pop", liked: false, singer: "Diljit Dosanjh, Nikhita Gandhi"},
  {id: 34, name: "Kudiyee Ni Teri", song: song34, image: image34, category: "Party, Dance", liked: false, singer: "The PropheC, Zahrah S Khan"},
  {id: 35, name: "Pehle Bhi Main", song: song35, image: image35, category: "Romantic", liked: false, singer: "Vishal Mishra"},
  {id: 36, name: "Zihaal e Miskin", song: song36, image: image36, category: "Romantic, Classical Vibe", liked: false, singer: "Shreya Ghoshal, Vishal Mishra"},
  {id: 37, name: "Barsaat Aa Gayi", song: song37, image: image37, category: "Romantic", liked: false, singer: "Shreya Ghoshal, Stebin Ben"},
  {id: 38, name: "Saawan Aa Gaya", song: song38, image: image38, category: "Romantic", liked: false, singer: "Neha Kakkar, Rohanpreet Singh"},
  {id: 39, name: "Achha Sila Diya", song: song39, image: image39, category: "Sad", liked: false, singer: "B Praak"},
  {id: 40, name: "Heeriye", song: song40, image: image40, category: "Romantic", liked: false, singer: "Arijit Singh, Jasleen Royal"},
  {id: 41, name: "Pyaar Hota Kayi Baar Hai", song: song41, image: image41, category: "Fun, Romantic", liked: false, singer: "Arijit Singh"},
  {id: 42, name: "Nasha", song: song42, image: image42, category: "Party, Dance", liked: false, singer: "Amir Jalal"},
  {id: 43, name: "Tum Se", song: song43, image: image43, category: "Romantic", liked: false, singer: "Arijit Singh"},
  {id: 44, name: "Humnava", song: song44, image: image44, category: "Soulful, Romantic", liked: false, singer: "Papon"},
  {id: 45, name: "Tujh Mein Rab Dikhta Hai (2024 Reprise)", song: song45, image: image45, category: "Devotional Love", liked: false, singer: "Arijit Singh"},
  {id: 46, name: "Ishq Tera Tadpave (Recreated)", song: song46, image: image46, category: "Party, Dance", liked: false, singer: "Hardy Sandhu"},
  {id: 47, name: "Rubicon Drill", song: song47, image: image47, category: "Hip-Hop", liked: false, singer: "Karun Aujla"},
  {id: 48, name: "Ve Kamleya", song: song48, image: image48, category: "Romantic", liked: false, singer: "Arijit Singh, Shreya Ghoshal"},
  {id: 49, name: "Dil Haar Da", song: song49, image: image49, category: "Romantic", liked: false, singer: "Darshan Raval"},
  {id: 50, name: "Kya Baat Ay 2.0", song: song50, image: image50, category: "Dance, Party", liked: false, singer: "Harrdy Sandhu"},
  {id: 51, name: "Dil Diyan Gallan (Reprise)", song: song51, image: image51, category: "Romantic", liked: false, singer: "Atif Aslam"},
  {id: 52, name: "Baazigar", song: song52, image: image52, category: "Rap, Hip-Hop", liked: false, singer: "DIVINE, Armani White"},
  {id: 53, name: "Saiyaan", song: song53, image: image53, category: "Devotional, Folk", liked: false, singer: "Kailash Kher"},
  {id: 54, name: "Nadiyon Paar (Let The Music Play Again)", song: song54, image: image54, category: "Party, Dance", liked: false, singer: "Rashmeet Kaur, Shamur"},
  {id: 55, name: "Mehabooba (KGF 2 Hindi)", song: song55, image: image55, category: "Romantic", liked: false, singer: "Ananya Bhat"},
  {id: 56, name: "Dhol Bajaa", song: song56, image: image56, category: "Festive, Dance", liked: false, singer: "Neha Kakkar, Tony Kakkar"},
  {id: 57, name: "Kya Loge Tum", song: song57, image: image57, category: "Sad", liked: false, singer: "B Praak, Jaani"},
  {id: 58, name: "Guli Mata", song: song58, image: image58, category: "Romantic, World Music", liked: false, singer: "Saad Lamjarred"},
  {id: 59, name: "Doobey", song: song59, image: image59, category: "Chill, Romantic", liked: false, singer: "Lothika"},
  {id: 60, name: "Raataan Lambiyan (Lo-Fi)", song: song60, image: image60, category: "Lo-Fi, Romantic", liked: false, singer: "Jubin Nautiyal, Asees Kaur"},
  {id: 61, name: "Kinna Sona (Remix)", song: song61, image: image61, category: "Romantic, Remix", liked: false, singer: "Dhvani Bhanushali, Jubin Nautiyal"},
  {id: 62, name: "O Saathiya", song: song62, image: image62, category: "Romantic", liked: false, singer: "Arijit Singh, Zahrah Khan"},
  {id: 63, name: "Saari Duniya Jalaa Denge", song: song63, image: image63, category: "Intense, Sad", liked: false, singer: "B Praak"},
  {id: 64, name: "Rehnuma", song: song64, image: image64, category: "Soulful, Romantic", liked: false, singer: "Arijit Singh, Shilpa Rao"},
  {id: 65, name: "Pehli Dafa (Recreated)", song: song65, image: image65, category: "Romantic", liked: false, singer: "Atif Aslam"},
  {id: 66, name: "Khairiyat (New Version)", song: song66, image: image66, category: "Romantic, Emotional", liked: false, singer: "Arijit Singh"},
  {id: 67, name: "Judaaiyaan", song: song67, image: image67, category: "Sad, Emotional", liked: false, singer: "Darshan Raval, Shreya Ghoshal"},
  {id: 68, name: "Tera Ban Jaunga (Reprise)", song: song68, image: image68, category: "Romantic", liked: false, singer: "Tulsi Kumar"},
  {id: 69, name: "Dil Ka Telephone 2.0", song: song69, image: image69, category: "Fun, Dance", liked: false, singer: "Jonita Gandhi, Nakash Aziz"},
  {id: 70, name: "Jhootha Pyar", song: song70, image: image70, category: "Sad, Romantic", liked: false, singer: "Neha Kakkar"},
  {id: 71, name: "Ghar More Pardesiya (Remastered)", song: song71, image: image71, category: "Classical, Devotional", liked: false, singer: "Shreya Ghoshal"},
  {id: 72, name: "Lagdi Lahore Di (Remix)", song: song72, image: image72, category: "Dance, Party", liked: false, singer: "Guru Randhawa"},
  {id: 73, name: "Paagal", song: song73, image: image73, category: "Party, Dance", liked: false, singer: "Badshah"},
  {id: 74, name: "Tip Tip (Remix)", song: song74, image: image74, category: "Dance, Nostalgic", liked: false, singer: "Udit Narayan, Alka Yagnik"},
  {id: 75, name: "Jugnu", song: song75, image: image75, category: "Dance, Pop", liked: false, singer: "Badshah, Nikhita Gandhi"}
];
